package com.face.model;

import java.util.Date;

public class Session {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.role
     *
     * @mbg.generated
     */
    
    private Integer role;
    private String roleName;
    private String userIdString;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.last_active_time
     *
     * @mbg.generated
     */
    private Date lastActiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.last_capture_time
     *
     * @mbg.generated
     */
    private Date lastCaptureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_session.last_alarm_time
     *
     * @mbg.generated
     */
    private Date lastAlarmTime;

    public Session() {

    }
    
    public Session(String token, User user) {
        this.token = token;
        this.userId = user.getId();
        this.role = user.getRole();
        this.deptId = user.getDeptId();
        this.lastActiveTime = new Date();
        this.lastCaptureTime = new Date();
        this.lastAlarmTime = new Date();
    }

    public Session(String token, User user, String roleName) {
    	this(token, user);
        this.roleName = roleName;
        this.setUserIdString(user.getUsername());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.token
     *
     * @return the value of t_session.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.token
     *
     * @param token the value for t_session.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.user_id
     *
     * @return the value of t_session.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.user_id
     *
     * @param userId the value for t_session.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.role
     *
     * @return the value of t_session.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.role
     *
     * @param role the value for t_session.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUserIdString() {
		return userIdString;
	}

	public void setUserIdString(String userIdString) {
		this.userIdString = userIdString;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.dept_id
     *
     * @return the value of t_session.dept_id
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.dept_id
     *
     * @param deptId the value for t_session.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.last_active_time
     *
     * @return the value of t_session.last_active_time
     *
     * @mbg.generated
     */
    public Date getLastActiveTime() {
        return lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.last_active_time
     *
     * @param lastActiveTime the value for t_session.last_active_time
     *
     * @mbg.generated
     */
    public void setLastActiveTime(Date lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.last_capture_time
     *
     * @return the value of t_session.last_capture_time
     *
     * @mbg.generated
     */
    public Date getLastCaptureTime() {
        return lastCaptureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.last_capture_time
     *
     * @param lastCaptureTime the value for t_session.last_capture_time
     *
     * @mbg.generated
     */
    public void setLastCaptureTime(Date lastCaptureTime) {
        this.lastCaptureTime = lastCaptureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_session.last_alarm_time
     *
     * @return the value of t_session.last_alarm_time
     *
     * @mbg.generated
     */
    public Date getLastAlarmTime() {
        return lastAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_session.last_alarm_time
     *
     * @param lastAlarmTime the value for t_session.last_alarm_time
     *
     * @mbg.generated
     */
    public void setLastAlarmTime(Date lastAlarmTime) {
        this.lastAlarmTime = lastAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Session other = (Session) that;
        return (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getLastActiveTime() == null ? other.getLastActiveTime() == null : this.getLastActiveTime().equals(other.getLastActiveTime()))
            && (this.getLastCaptureTime() == null ? other.getLastCaptureTime() == null : this.getLastCaptureTime().equals(other.getLastCaptureTime()))
            && (this.getLastAlarmTime() == null ? other.getLastAlarmTime() == null : this.getLastAlarmTime().equals(other.getLastAlarmTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getLastActiveTime() == null) ? 0 : getLastActiveTime().hashCode());
        result = prime * result + ((getLastCaptureTime() == null) ? 0 : getLastCaptureTime().hashCode());
        result = prime * result + ((getLastAlarmTime() == null) ? 0 : getLastAlarmTime().hashCode());
        return result;
    }
}