package com.face.model;

public class UserMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_menu.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_menu.user_menu
     *
     * @mbg.generated
     */
    private String userMenu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_menu.id
     *
     * @return the value of t_user_menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_menu.id
     *
     * @param id the value for t_user_menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_menu.user_id
     *
     * @return the value of t_user_menu.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_menu.user_id
     *
     * @param userId the value for t_user_menu.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_menu.user_menu
     *
     * @return the value of t_user_menu.user_menu
     *
     * @mbg.generated
     */
    public String getUserMenu() {
        return userMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_menu.user_menu
     *
     * @param userMenu the value for t_user_menu.user_menu
     *
     * @mbg.generated
     */
    public void setUserMenu(String userMenu) {
        this.userMenu = userMenu == null ? null : userMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_menu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserMenu other = (UserMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserMenu() == null ? other.getUserMenu() == null : this.getUserMenu().equals(other.getUserMenu()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_menu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserMenu() == null) ? 0 : getUserMenu().hashCode());
        return result;
    }
}