package com.face.mapper;

import com.face.model.Session;
import com.face.model.SessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    long countByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int deleteByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int insert(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int insertSelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    List<Session> selectByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    Session selectByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Session record);
}